version: "3"

services:
  vue:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    command: npm run serve
    volumes:
      - ./app:/app
    expose:
      - "8080"
    ports:
      - "8080:8080"
